### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by JCGoran**
Seeing as how Python 2 was [deprecated](https://www.python.org/doc/sunset-python-2/) this year, I've made some minimal changes which should hopefully make CosmicFish run under Python 3+ as well.

Note that there's still one last thing that needs to be fixed when running tests:
```python
line 163, in search_fisher_path:
    if CosmicFishPyLib.__feedback__ > 1: print('Trying to import: '+file+' as a Fisher matrix: ', end=' ')
AttributeError: 'method-wrapper' object has no attribute '__feedback__'
```
which *I think* has something to do with the lack of [unbound methods](https://stackoverflow.com/questions/10401935/python-method-wrapper-type) in Python 3, and don't really know how to fix properly.

Other than that, there could be some inadvertent lack of float rounding in the ticks of the plots, which can be easily fixed, a minimal diff example is attached.
[formatting.patch](https://github.com/CosmicFish/CosmicFish/files/4187331/formatting.txt)

### CODE REVIEW

**Comment by matmartinelli** [comment]
Hello @JCGoran thanks for this fix! We will have a look at this and merge it asap.

I am currently working on a complete restructuring of the fortran source of CosmicFish, which will also be written in python3. So this update is very timely

**Comment by JCGoran** [comment]
Hi @matmartinelli 
If there's a major restructuring underway, then I'm guessing most of my changes won't apply to the new codebase, so in case I have any other pull requests, should I then submit them or not?
In either case, I will of course keep any useful changes to the current (public) version of the code in my fork.

**Comment by matmartinelli** [comment]
Hi @JCGoran the restructuring will affect the current fortran part (calculation of the matrices) and the interface with CAMB. As far as I can see you are currently editing only the analysis part of the code, which is already in python. I will probably change the interface of this with the rest of the code, but not the rest (at least not for now).

So you can definitely submit other merge requests for the analysis part.
I hope to have time to merge it soon!

**Comment by JCGoran** [comment]
Good to know, I'm currently focusing on the analysis part anyway.

**Comment by mraveri** [comment]
Hi @JCGoran thank you for this, Travis is not happy but I am going to merge and solve the residual problems!

**Pull request merged**
